### ISSUE TITLE
TypeError: graph.selection[0] is undefined

### ISSUE THREAD

**Issue by remyla** [PRIMCODE/damas-flow#22]
in interactions.js, line 148

how to reproduce the bug:

when selecting 2 nodes, then press `l` key to make a link

the reason: the damas.create() method is asynchronous, and graph.unselectAll is called outside the callback, but inside the callback we have a console.log who wants to display the linked nodes 

@jogal360

**Comment by jogal360** [comment]
Fix in: https://github.com/PRIMCODE/damas-flow/commit/f964df1fbfd805a4b502faa3ad34cce561d86166
